Add rational-osx.el module
SystemCrafters/rational-emacs pull request #170
Opened 2022-07-02 19:35 UTC by saccarosium

Adds:
* Option to make macOS titlebar transparent;
* Sane configuration for macOS specific modifiers (opt, command);
* Some keybinding involving the command key for making the all experience more
  consistent with macOS default ones

All the new keybindings are bound to hyper, so they don't overwrite the default
ones.

2022-07-04 15:04 UTC, jeffbowman commented
Thanks! Just a small request to update the header of the module to match the rest of the modules.

2022-07-04 15:04 UTC, jeffbowman requested changes

2022-07-04 22:14 UTC, saccarosium commented
Should be right now.

2022-07-05 02:11 UTC, jeffbowman approved these changes

2022-07-05 02:15 UTC, merged