Make some improvements in rational-evil.el
SystemCrafters/rational-emacs pull request #171
Opened 2022-07-02 20:16 UTC by saccarosium

I have added a variable (`rational-evil-vim-muscle-memory`) that let you make Emacs at little more like vim.

2022-07-04 15:06 UTC, jeffbowman commented
Could you split this PR into just the portion for your improvements to `rational-evil`, it currently includes the PR for your OSX submission.

2022-07-04 15:08 UTC, jeffbowman requested changes

2022-07-04 22:26 UTC, saccarosium commented
I split the commits

2022-07-05 02:12 UTC, jeffbowman approved these changes

2022-07-05 02:15 UTC, merged